/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:slider1:502039:
  println("slider1 - GSlider >> GEvent." + event + " @ " + millis());
  N = source.getValueI();
  textfield1.setText(""+N);
} //_CODE_:slider1:502039:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:222052:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
  if(event == GEvent.LOST_FOCUS)
  {
          
     N = source.getValueI();
     slider1.setValue(N);
     textfield1.setText(""+N);
  }
} //_CODE_:textfield1:222052:

public void slider2_change1(GSlider source, GEvent event) { //_CODE_:slider2:990779:
  println("slider2 - GSlider >> GEvent." + event + " @ " + millis());
  C = source.getValueI();
  textfield2.setText(""+C);
} //_CODE_:slider2:990779:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:textfield2:991719:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
  if(event == GEvent.LOST_FOCUS)
  {
          
     C = source.getValueI();
     slider2.setValue(C);
     textfield2.setText(""+C);
  }
} //_CODE_:textfield2:991719:

public void slider3_change1(GSlider source, GEvent event) { //_CODE_:slider3:600862:
  println("slider3 - GSlider >> GEvent." + event + " @ " + millis());
  Cl = source.getValueI();
  textfield3.setText(""+Cl);
} //_CODE_:slider3:600862:

public void slider4_change1(GSlider source, GEvent event) { //_CODE_:slider4:983751:
  println("slider4 - GSlider >> GEvent." + event + " @ " + millis());
  T = source.getValueI();
  textfield4.setText(""+T);
} //_CODE_:slider4:983751:

public void slider5_change1(GSlider source, GEvent event) { //_CODE_:slider5:372345:
  println("slider5 - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:slider5:372345:

public void textfield3_change1(GTextField source, GEvent event) { //_CODE_:textfield3:807157:
  println("textfield3 - GTextField >> GEvent." + event + " @ " + millis());
  if(event == GEvent.LOST_FOCUS)
  {
          
     Cl = source.getValueI();
     slider3.setValue(Cl);
     textfield3.setText(""+Cl);
  }
} //_CODE_:textfield3:807157:

public void textfield4_change1(GTextField source, GEvent event) { //_CODE_:textfield4:379041:
  println("textfield4 - GTextField >> GEvent." + event + " @ " + millis());
  if(event == GEvent.LOST_FOCUS)
  {
          
     T = source.getValueI();
     slider4.setValue(T);
     textfield4.setText(""+T);
  }
} //_CODE_:textfield4:379041:

public void textfield5_change1(GTextField source, GEvent event) { //_CODE_:textfield5:541669:
  println("textfield5 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield5:541669:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:982747:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  students = new Student[N];
  for(int i = 0; i < students.length; i++)
  {
    students[i] = new Student(0, 0, C, Cl);
  }
  state = 1;
} //_CODE_:button1:982747:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.RED_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  slider1 = new GSlider(this, 200, 100, 300, 100, 10.0);
  slider1.setShowValue(true);
  slider1.setShowLimits(true);
  slider1.setLimits(1000, 20, 10000);
  slider1.setNumberFormat(G4P.INTEGER, 0);
  slider1.setOpaque(false);
  slider1.addEventHandler(this, "slider1_change1");
  
  textfield1 = new GTextField(this, 600, 130, 200, 30, G4P.SCROLLBARS_NONE);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  textfield1.setNumeric(0, 10000, 1000);
  textfield1.setFont(new Font("Sans-serif", Font.BOLD, 24));
  slider2 = new GSlider(this, 200, 200, 300, 100, 10.0);
  slider2.setShowValue(true);
  slider2.setShowLimits(true);
  slider2.setLimits(6, 1, 20);
  slider2.setNumberFormat(G4P.INTEGER, 0);
  slider2.setOpaque(false);
  slider2.addEventHandler(this, "slider2_change1");
  textfield2 = new GTextField(this, 600, 230, 200, 30, G4P.SCROLLBARS_NONE);
  textfield2.setOpaque(true);
  textfield2.addEventHandler(this, "textfield2_change1");
  textfield2.setNumeric(1, 20, 6);
  textfield2.setFont(new Font("Sans-serif", Font.BOLD, 24));
  slider3 = new GSlider(this, 200, 300, 300, 100, 10.0);
  slider3.setShowValue(true);
  slider3.setShowLimits(true);
  slider3.setLimits(80, 1, 200);
  slider3.setNumberFormat(G4P.INTEGER, 0);
  slider3.setOpaque(false);
  slider3.addEventHandler(this, "slider3_change1");
  slider4 = new GSlider(this, 200, 400, 300, 100, 10.0);
  slider4.setShowValue(true);
  slider4.setShowLimits(true);
  slider4.setLimits(180, 30, 500);
  slider4.setNumberFormat(G4P.INTEGER, 0);
  slider4.setOpaque(false);
  slider4.addEventHandler(this, "slider4_change1");
  slider5 = new GSlider(this, 200, 500, 300, 98, 10.0);
  slider5.setLimits(0.5, 0.0, 1.0);
  slider5.setNumberFormat(G4P.DECIMAL, 2);
  slider5.setOpaque(false);
  slider5.addEventHandler(this, "slider5_change1");
  textfield3 = new GTextField(this, 600, 330, 200, 30, G4P.SCROLLBARS_NONE);
  textfield3.setOpaque(true);
  textfield3.addEventHandler(this, "textfield3_change1");
  textfield3.setNumeric(1, 200, 80);
  textfield3.setFont(new Font("Sans-serif", Font.BOLD, 24));
  textfield4 = new GTextField(this, 600, 430, 200, 30, G4P.SCROLLBARS_NONE);
  textfield4.setOpaque(true);
  textfield4.addEventHandler(this, "textfield4_change1");
  textfield4.setNumeric(30, 500, 180);
  textfield4.setFont(new Font("Sans-serif", Font.BOLD, 24));
  textfield5 = new GTextField(this, 600, 530, 200, 30, G4P.SCROLLBARS_NONE);
  textfield5.setOpaque(true);
  textfield5.addEventHandler(this, "textfield5_change1");
  button1 = new GButton(this, 200, 630, 600, 70);
  button1.setText("Start!");
  button1.addEventHandler(this, "button1_click1");
  label1 = new GLabel(this, 0, 100, 200, 100);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("# of students:");
  label1.setOpaque(false);
  label1.setFont(new Font("Sans ", Font.BOLD, 28));
  label2 = new GLabel(this, 0, 200, 200, 100);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("# of periods/day:");
  label2.setOpaque(false);
  label2.setFont(new Font("SansSerif", Font.BOLD, 28));
  label3 = new GLabel(this, 0, 300, 200, 100);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("# of classrooms:");
  label3.setOpaque(false);
  label3.setFont(new Font("SansSerif", Font.BOLD, 28));
  label4 = new GLabel(this, 0, 400, 200, 100);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Days of simulation:");
  label4.setOpaque(false);
  label4.setFont(new Font("SansSerif", Font.BOLD, 28));
  label5 = new GLabel(this, 0, 500, 200, 100);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("out of order");
  label5.setOpaque(false);
  label5.setFont(new Font("SansSerif", Font.BOLD, 28));
}

// Variable declarations 
// autogenerated do not edit
GSlider slider1; 
GTextField textfield1; 
GSlider slider2; 
GTextField textfield2; 
GSlider slider3; 
GSlider slider4; 
GSlider slider5; 
GTextField textfield3; 
GTextField textfield4; 
GTextField textfield5; 
GButton button1; 
GLabel label1; 
GLabel label2; 
GLabel label3; 
GLabel label4; 
GLabel label5; 
